/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Domain.Vehicle;
import File.VehicleFile;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Nelson
 */
public class insertVehicle extends javax.swing.JFrame {

    /**
     * Creates new form insertVehicle
     */
    public insertVehicle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfd_year = new javax.swing.JTextField();
        tfd_name = new javax.swing.JTextField();
        tfd_mileage = new javax.swing.JTextField();
        tfd_american = new javax.swing.JTextField();
        tfd_series = new javax.swing.JTextField();
        btn_insertVehicle = new javax.swing.JButton();
        btn_updateVehicle = new javax.swing.JButton();
        btn_deleteVehicle = new javax.swing.JButton();
        btn_listVehicles = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        lbl_mileage = new javax.swing.JLabel();
        lbl_year = new javax.swing.JLabel();
        lbl_american = new javax.swing.JLabel();
        lbl_series = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_insertVehicle.setText("Insert");
        btn_insertVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertVehicleActionPerformed(evt);
            }
        });

        btn_updateVehicle.setText("Update");

        btn_deleteVehicle.setText("Delete");

        btn_listVehicles.setText("List Vehicles");
        btn_listVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listVehiclesActionPerformed(evt);
            }
        });

        lbl_name.setText("Name");

        lbl_mileage.setText("Mileage");

        lbl_year.setText("Year");

        lbl_american.setText("American");

        lbl_series.setText("Series");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_series)
                    .addComponent(lbl_american)
                    .addComponent(lbl_name)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_year, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_mileage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_deleteVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfd_series, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(tfd_american, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(tfd_mileage, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(tfd_year)
                    .addComponent(btn_insertVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_updateVehicle)
                    .addComponent(btn_listVehicles))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(163, 163, 163)
                    .addComponent(tfd_name, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(167, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbl_name)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfd_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_year))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfd_mileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_mileage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfd_american, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_american))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfd_series, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_series))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insertVehicle)
                    .addComponent(btn_updateVehicle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_deleteVehicle)
                    .addComponent(btn_listVehicles)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(tfd_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(236, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertVehicleActionPerformed
        // TODO add your handling code here:
        //capturar lo del txfield
        
        
        
        
        try{
        
            File file= new File("./vehicle.dat");
            VehicleFile vehicleFile = new VehicleFile(file);
            String nameV= tfd_name.getText();
            int yearV= Integer.parseInt(tfd_year.getText());
            float mileageV= Float.parseFloat(tfd_mileage.getText());
            boolean americanV= Boolean.parseBoolean(tfd_american.getText());
            int seriesV= Integer.parseInt(tfd_series.getText());

            Vehicle vehiculo = new Vehicle(nameV, yearV, mileageV, americanV, seriesV);
            //aqui se inserta el vehiculo
            vehicleFile.addEndRecord(vehiculo);
        
        }catch(IOException ioe){
        
        }
        
    }//GEN-LAST:event_btn_insertVehicleActionPerformed

    private void btn_listVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listVehiclesActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_btn_listVehiclesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertVehicle().setVisible(true);
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deleteVehicle;
    private javax.swing.JButton btn_insertVehicle;
    private javax.swing.JButton btn_listVehicles;
    private javax.swing.JButton btn_updateVehicle;
    private javax.swing.JLabel lbl_american;
    private javax.swing.JLabel lbl_mileage;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_series;
    private javax.swing.JLabel lbl_year;
    private javax.swing.JTextField tfd_american;
    private javax.swing.JTextField tfd_mileage;
    private javax.swing.JTextField tfd_name;
    private javax.swing.JTextField tfd_series;
    private javax.swing.JTextField tfd_year;
    // End of variables declaration//GEN-END:variables
}
